export type ThemeConfig = {
  id: string;
  name: string;
  description: string;
  category: string;
  categoryLabel: string;
  preview: {
    bg: string;
    accent: string;
    text: string;
    card: string;
  };
  styles: {
    pageBg: string;
    pageBgGradient?: string;
    headingColor: string;
    textColor: string;
    mutedColor: string;
    avatarRing: string;
    avatarFallback: string;
    avatarFallbackText: string;
    socialIconColor: string;
    socialIconHover: string;
    cardBg: string;
    cardBorder: string;
    cardHoverShadow: string;
    cardHoverBorder: string;
    priceColor: string;
    linkColor: string;
    linkHoverColor: string;
    productBadge: string;
    productBadgeText: string;
    footerColor: string;
    buttonBg: string;
    buttonText: string;
  };
};

export type ThemeCategory = {
  id: string;
  label: string;
  defaultVariant: string;
  variants: ThemeConfig[];
};

export const themes: ThemeConfig[] = [
  {
    id: 'light-clean-classic',
    name: 'Classic Blue',
    description: 'Balanced, trustworthy, universal SaaS style',
    category: 'light-clean',
    categoryLabel: 'Light Clean',
    preview: { bg: '#F9FAFB', accent: '#2563EB', text: '#111827', card: '#FFFFFF' },
    styles: {
      pageBg: '#F9FAFB',
      pageBgGradient: 'linear-gradient(to bottom, #F9FAFB, #F3F4F6)',
      headingColor: '#111827',
      textColor: '#6B7280',
      mutedColor: '#9CA3AF',
      avatarRing: '#FFFFFF',
      avatarFallback: '#EFF6FF',
      avatarFallbackText: '#2563EB',
      socialIconColor: '#9CA3AF',
      socialIconHover: '#2563EB',
      cardBg: '#FFFFFF',
      cardBorder: '#E5E7EB',
      cardHoverShadow: '0 4px 12px rgba(37,99,235,0.1)',
      cardHoverBorder: '#2563EB',
      priceColor: '#111827',
      linkColor: '#2563EB',
      linkHoverColor: '#93C5FD',
      productBadge: 'linear-gradient(135deg, #2563EB, #93C5FD)',
      productBadgeText: '#FFFFFF',
      footerColor: '#D1D5DB',
      buttonBg: '#2563EB',
      buttonText: '#FFFFFF',
    },
  },
  {
    id: 'light-clean-teal',
    name: 'Teal Modern',
    description: 'Notion / Linear vibe, fresh and modern',
    category: 'light-clean',
    categoryLabel: 'Light Clean',
    preview: { bg: '#F0FDFA', accent: '#14B8A6', text: '#042F2E', card: '#FFFFFF' },
    styles: {
      pageBg: '#F0FDFA',
      pageBgGradient: 'linear-gradient(to bottom, #F0FDFA, #CCFBF1)',
      headingColor: '#042F2E',
      textColor: '#0F766E',
      mutedColor: '#99F6E4',
      avatarRing: '#FFFFFF',
      avatarFallback: '#CCFBF1',
      avatarFallbackText: '#14B8A6',
      socialIconColor: '#5EEAD4',
      socialIconHover: '#0F766E',
      cardBg: '#FFFFFF',
      cardBorder: '#CCFBF1',
      cardHoverShadow: '0 4px 12px rgba(20,184,166,0.1)',
      cardHoverBorder: '#14B8A6',
      priceColor: '#042F2E',
      linkColor: '#14B8A6',
      linkHoverColor: '#99F6E4',
      productBadge: 'linear-gradient(135deg, #14B8A6, #99F6E4)',
      productBadgeText: '#FFFFFF',
      footerColor: '#99F6E4',
      buttonBg: '#14B8A6',
      buttonText: '#FFFFFF',
    },
  },
  {
    id: 'light-clean-pastel',
    name: 'Soft Pastel Mix',
    description: 'Friendly vibe, creator friendly',
    category: 'light-clean',
    categoryLabel: 'Light Clean',
    preview: { bg: '#FDFCFB', accent: '#60A5FA', text: '#1F2937', card: '#FFFFFF' },
    styles: {
      pageBg: '#FDFCFB',
      pageBgGradient: 'linear-gradient(to bottom, #FDFCFB, #FEF3C7)',
      headingColor: '#1F2937',
      textColor: '#9CA3AF',
      mutedColor: '#D1D5DB',
      avatarRing: '#FFFFFF',
      avatarFallback: '#EFF6FF',
      avatarFallbackText: '#60A5FA',
      socialIconColor: '#D1D5DB',
      socialIconHover: '#60A5FA',
      cardBg: '#FFFFFF',
      cardBorder: '#F3F4F6',
      cardHoverShadow: '0 4px 12px rgba(96,165,250,0.1)',
      cardHoverBorder: '#60A5FA',
      priceColor: '#1F2937',
      linkColor: '#60A5FA',
      linkHoverColor: '#F9A8D4',
      productBadge: 'linear-gradient(135deg, #60A5FA, #F9A8D4)',
      productBadgeText: '#FFFFFF',
      footerColor: '#E5E7EB',
      buttonBg: '#60A5FA',
      buttonText: '#FFFFFF',
    },
  },
  {
    id: 'light-clean-neutral',
    name: 'Neutral Gray',
    description: 'Premium minimal, boring but powerful',
    category: 'light-clean',
    categoryLabel: 'Light Clean',
    preview: { bg: '#FAFAFA', accent: '#18181B', text: '#18181B', card: '#FFFFFF' },
    styles: {
      pageBg: '#FAFAFA',
      pageBgGradient: 'linear-gradient(to bottom, #FAFAFA, #F5F5F5)',
      headingColor: '#18181B',
      textColor: '#71717A',
      mutedColor: '#A1A1AA',
      avatarRing: '#FFFFFF',
      avatarFallback: '#F4F4F5',
      avatarFallbackText: '#18181B',
      socialIconColor: '#A1A1AA',
      socialIconHover: '#18181B',
      cardBg: '#FFFFFF',
      cardBorder: '#E4E4E7',
      cardHoverShadow: '0 4px 12px rgba(0,0,0,0.08)',
      cardHoverBorder: '#18181B',
      priceColor: '#18181B',
      linkColor: '#18181B',
      linkHoverColor: '#A1A1AA',
      productBadge: '#18181B',
      productBadgeText: '#FFFFFF',
      footerColor: '#D4D4D8',
      buttonBg: '#18181B',
      buttonText: '#FFFFFF',
    },
  },
  {
    id: 'dark-minimal',
    name: 'Dark Minimal',
    description: 'Deep dark with indigo accents',
    category: 'dark-minimal',
    categoryLabel: 'Dark Minimal',
    preview: { bg: '#0F1115', accent: '#6366F1', text: '#FFFFFF', card: '#1A1D24' },
    styles: {
      pageBg: '#0F1115',
      pageBgGradient: 'linear-gradient(to bottom, #0F1115, #1A1D24)',
      headingColor: '#FFFFFF',
      textColor: '#A1A1AA',
      mutedColor: '#71717A',
      avatarRing: '#1A1D24',
      avatarFallback: '#1E1B4B',
      avatarFallbackText: '#6366F1',
      socialIconColor: '#71717A',
      socialIconHover: '#A1A1AA',
      cardBg: '#1A1D24',
      cardBorder: '#27272A',
      cardHoverShadow: '0 4px 16px rgba(99,102,241,0.15)',
      cardHoverBorder: '#6366F1',
      priceColor: '#FFFFFF',
      linkColor: '#6366F1',
      linkHoverColor: '#8B5CF6',
      productBadge: 'linear-gradient(135deg, #6366F1, #8B5CF6)',
      productBadgeText: '#FFFFFF',
      footerColor: '#27272A',
      buttonBg: '#6366F1',
      buttonText: '#FFFFFF',
    },
  },
  {
    id: 'warm-sunset',
    name: 'Warm Sunset',
    description: 'Dark stone with warm orange glow',
    category: 'warm-sunset',
    categoryLabel: 'Warm Sunset',
    preview: { bg: '#1C1917', accent: '#F97316', text: '#FFF7ED', card: '#292524' },
    styles: {
      pageBg: '#1C1917',
      pageBgGradient: 'linear-gradient(to bottom, #1C1917, #292524)',
      headingColor: '#FFF7ED',
      textColor: '#FDBA74',
      mutedColor: '#9A3412',
      avatarRing: '#292524',
      avatarFallback: '#431407',
      avatarFallbackText: '#F97316',
      socialIconColor: '#9A3412',
      socialIconHover: '#FDBA74',
      cardBg: '#292524',
      cardBorder: '#44403C',
      cardHoverShadow: '0 4px 16px rgba(249,115,22,0.2)',
      cardHoverBorder: '#F97316',
      priceColor: '#FFF7ED',
      linkColor: '#F97316',
      linkHoverColor: '#FB923C',
      productBadge: 'linear-gradient(135deg, #F97316, #FB923C)',
      productBadgeText: '#FFFFFF',
      footerColor: '#44403C',
      buttonBg: '#F97316',
      buttonText: '#FFFFFF',
    },
  },
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    description: 'Deep navy with sky blue highlights',
    category: 'ocean-breeze',
    categoryLabel: 'Ocean Breeze',
    preview: { bg: '#0A192F', accent: '#38BDF8', text: '#E6F1FF', card: '#112240' },
    styles: {
      pageBg: '#0A192F',
      pageBgGradient: 'linear-gradient(to bottom, #0A192F, #112240)',
      headingColor: '#E6F1FF',
      textColor: '#8892B0',
      mutedColor: '#495670',
      avatarRing: '#112240',
      avatarFallback: '#0C4A6E',
      avatarFallbackText: '#38BDF8',
      socialIconColor: '#495670',
      socialIconHover: '#8892B0',
      cardBg: '#112240',
      cardBorder: '#1D3461',
      cardHoverShadow: '0 4px 16px rgba(56,189,248,0.15)',
      cardHoverBorder: '#38BDF8',
      priceColor: '#E6F1FF',
      linkColor: '#38BDF8',
      linkHoverColor: '#0EA5E9',
      productBadge: 'linear-gradient(135deg, #38BDF8, #0EA5E9)',
      productBadgeText: '#0A192F',
      footerColor: '#1D3461',
      buttonBg: '#38BDF8',
      buttonText: '#0A192F',
    },
  },
  {
    id: 'nature-soft',
    name: 'Nature Soft',
    description: 'Fresh greens on light background',
    category: 'nature-soft',
    categoryLabel: 'Nature Soft',
    preview: { bg: '#F0FDF4', accent: '#22C55E', text: '#14532D', card: '#DCFCE7' },
    styles: {
      pageBg: '#F0FDF4',
      pageBgGradient: 'linear-gradient(to bottom, #F0FDF4, #DCFCE7)',
      headingColor: '#14532D',
      textColor: '#4D7C0F',
      mutedColor: '#86EFAC',
      avatarRing: '#DCFCE7',
      avatarFallback: '#DCFCE7',
      avatarFallbackText: '#22C55E',
      socialIconColor: '#86EFAC',
      socialIconHover: '#14532D',
      cardBg: '#DCFCE7',
      cardBorder: '#BBF7D0',
      cardHoverShadow: '0 4px 12px rgba(34,197,94,0.15)',
      cardHoverBorder: '#22C55E',
      priceColor: '#14532D',
      linkColor: '#22C55E',
      linkHoverColor: '#86EFAC',
      productBadge: 'linear-gradient(135deg, #22C55E, #86EFAC)',
      productBadgeText: '#FFFFFF',
      footerColor: '#BBF7D0',
      buttonBg: '#22C55E',
      buttonText: '#FFFFFF',
    },
  },
  {
    id: 'purple-dream',
    name: 'Purple Dream',
    description: 'Deep indigo with violet accents',
    category: 'purple-dream',
    categoryLabel: 'Purple Dream',
    preview: { bg: '#1E1B4B', accent: '#8B5CF6', text: '#E0E7FF', card: '#312E81' },
    styles: {
      pageBg: '#1E1B4B',
      pageBgGradient: 'linear-gradient(to bottom, #1E1B4B, #312E81)',
      headingColor: '#E0E7FF',
      textColor: '#A5B4FC',
      mutedColor: '#6366F1',
      avatarRing: '#312E81',
      avatarFallback: '#312E81',
      avatarFallbackText: '#8B5CF6',
      socialIconColor: '#6366F1',
      socialIconHover: '#A5B4FC',
      cardBg: '#312E81',
      cardBorder: '#4338CA',
      cardHoverShadow: '0 4px 16px rgba(139,92,246,0.2)',
      cardHoverBorder: '#8B5CF6',
      priceColor: '#E0E7FF',
      linkColor: '#8B5CF6',
      linkHoverColor: '#A78BFA',
      productBadge: 'linear-gradient(135deg, #8B5CF6, #A78BFA)',
      productBadgeText: '#FFFFFF',
      footerColor: '#4338CA',
      buttonBg: '#8B5CF6',
      buttonText: '#FFFFFF',
    },
  },
  {
    id: 'pink-soft',
    name: 'Pink Soft UI',
    description: 'Soft pink tones with rose highlights',
    category: 'pink-soft',
    categoryLabel: 'Pink Soft UI',
    preview: { bg: '#FFF1F2', accent: '#EC4899', text: '#881337', card: '#FFE4E6' },
    styles: {
      pageBg: '#FFF1F2',
      pageBgGradient: 'linear-gradient(to bottom, #FFF1F2, #FFE4E6)',
      headingColor: '#881337',
      textColor: '#BE185D',
      mutedColor: '#FDA4AF',
      avatarRing: '#FFE4E6',
      avatarFallback: '#FCE7F3',
      avatarFallbackText: '#EC4899',
      socialIconColor: '#FDA4AF',
      socialIconHover: '#BE185D',
      cardBg: '#FFE4E6',
      cardBorder: '#FECDD3',
      cardHoverShadow: '0 4px 12px rgba(236,72,153,0.15)',
      cardHoverBorder: '#EC4899',
      priceColor: '#881337',
      linkColor: '#EC4899',
      linkHoverColor: '#F472B6',
      productBadge: 'linear-gradient(135deg, #EC4899, #F472B6)',
      productBadgeText: '#FFFFFF',
      footerColor: '#FECDD3',
      buttonBg: '#EC4899',
      buttonText: '#FFFFFF',
    },
  },
  {
    id: 'black-gold',
    name: 'Black & Gold',
    description: 'Luxurious black with gold accents',
    category: 'black-gold',
    categoryLabel: 'Black & Gold',
    preview: { bg: '#0B0B0B', accent: '#D4AF37', text: '#FAFAFA', card: '#1A1A1A' },
    styles: {
      pageBg: '#0B0B0B',
      pageBgGradient: 'linear-gradient(to bottom, #0B0B0B, #1A1A1A)',
      headingColor: '#FAFAFA',
      textColor: '#A3A3A3',
      mutedColor: '#737373',
      avatarRing: '#1A1A1A',
      avatarFallback: '#1C1917',
      avatarFallbackText: '#D4AF37',
      socialIconColor: '#737373',
      socialIconHover: '#D4AF37',
      cardBg: '#1A1A1A',
      cardBorder: '#262626',
      cardHoverShadow: '0 4px 16px rgba(212,175,55,0.15)',
      cardHoverBorder: '#D4AF37',
      priceColor: '#FAFAFA',
      linkColor: '#D4AF37',
      linkHoverColor: '#FACC15',
      productBadge: 'linear-gradient(135deg, #D4AF37, #FACC15)',
      productBadgeText: '#0B0B0B',
      footerColor: '#262626',
      buttonBg: '#D4AF37',
      buttonText: '#0B0B0B',
    },
  },
  {
    id: 'glass-blue',
    name: 'Glass Blue',
    description: 'Frosted glass with sky blue',
    category: 'glass-blue',
    categoryLabel: 'Glass Blue',
    preview: { bg: '#E0F2FE', accent: '#0EA5E9', text: '#0C4A6E', card: '#FFFFFF' },
    styles: {
      pageBg: '#E0F2FE',
      pageBgGradient: 'linear-gradient(to bottom, #E0F2FE, #BAE6FD)',
      headingColor: '#0C4A6E',
      textColor: '#0369A1',
      mutedColor: '#7DD3FC',
      avatarRing: 'rgba(255,255,255,0.8)',
      avatarFallback: '#E0F2FE',
      avatarFallbackText: '#0EA5E9',
      socialIconColor: '#7DD3FC',
      socialIconHover: '#0369A1',
      cardBg: 'rgba(255,255,255,0.6)',
      cardBorder: 'rgba(14,165,233,0.2)',
      cardHoverShadow: '0 4px 16px rgba(14,165,233,0.12)',
      cardHoverBorder: '#0EA5E9',
      priceColor: '#0C4A6E',
      linkColor: '#0EA5E9',
      linkHoverColor: '#38BDF8',
      productBadge: 'linear-gradient(135deg, #0EA5E9, #38BDF8)',
      productBadgeText: '#FFFFFF',
      footerColor: '#BAE6FD',
      buttonBg: '#0EA5E9',
      buttonText: '#FFFFFF',
    },
  },
  {
    id: 'modern-neutral',
    name: 'Modern Neutral',
    description: 'Clean startup style with emerald',
    category: 'modern-neutral',
    categoryLabel: 'Modern Neutral',
    preview: { bg: '#F5F5F5', accent: '#10B981', text: '#171717', card: '#FFFFFF' },
    styles: {
      pageBg: '#F5F5F5',
      pageBgGradient: 'linear-gradient(to bottom, #F5F5F5, #E5E5E5)',
      headingColor: '#171717',
      textColor: '#737373',
      mutedColor: '#A3A3A3',
      avatarRing: '#FFFFFF',
      avatarFallback: '#ECFDF5',
      avatarFallbackText: '#10B981',
      socialIconColor: '#A3A3A3',
      socialIconHover: '#10B981',
      cardBg: '#FFFFFF',
      cardBorder: '#E5E5E5',
      cardHoverShadow: '0 4px 12px rgba(16,185,129,0.1)',
      cardHoverBorder: '#10B981',
      priceColor: '#171717',
      linkColor: '#10B981',
      linkHoverColor: '#34D399',
      productBadge: 'linear-gradient(135deg, #10B981, #34D399)',
      productBadgeText: '#FFFFFF',
      footerColor: '#D4D4D4',
      buttonBg: '#10B981',
      buttonText: '#FFFFFF',
    },
  },
];

export function getThemeCategories(): ThemeCategory[] {
  const map = new Map<string, ThemeConfig[]>();
  for (const t of themes) {
    const existing = map.get(t.category) || [];
    existing.push(t);
    map.set(t.category, existing);
  }
  return Array.from(map.entries()).map(([id, variants]) => ({
    id,
    label: variants[0].categoryLabel,
    defaultVariant: variants[0].id,
    variants,
  }));
}

export function getTheme(themeId: string): ThemeConfig {
  return themes.find((t) => t.id === themeId) || themes[0];
}
